### ISSUE TITLE
Use phpstan to improve code quality

### ISSUE THREAD

**Issue by robertfausk** [kevinkhill/php-duration#16]
see: https://github.com/phpstan/phpstan

e.g. new Duration() expects null via type hint which throws phpstan violations in projects using:
```PHP
$duration = new Duration(60);
```
when these projects use phpstan. At least in latest stable version ;) In master it is fixed.

e.g. 2: $housPerDay in constructor doesn't have a type hint.

**Comment by kevinkhill** [comment]
I've wanted to play with phpstan/psalm/phan but don't seem to ever have the time. If you want to integrate it into the project and add composer scripts to run it, I would happily accept a pull request.

**Comment by kevinkhill** [comment]
Thanks @AntonLazarev!
