### ISSUE TITLE
Add support for php8

### ISSUE THREAD

**Issue by Bodzix** [kevinkhill/php-duration#25]
When I try to install package in my project i got error:
`- Root composer.json requires php 7.3 but your php version (8.0.2) does not satisfy that requirement.`

Would you consider adding php8 support soon ?
Thanks in advance.

**Comment by michaljusiega** [comment]
See https://packagist.org/packages/khill/php-duration#1.1.0 
PHP-Duration support 5.4 and above. PHP8.0 too.

**Comment by Bodzix** [comment]
Sorry. Problem was in my composer.json. Not in package configuration.
Thank you @michaljusiega  !

**Comment by kevinkhill** [comment]
nice teamwork 👏🏻
