### ISSUE TITLE
Using days should be possible too

### ISSUE THREAD

**Issue by dimitri-koenig** [kevinkhill/php-duration#3]
Using days like "3d" should be possible too. Only catch is: you should also be able to tell how many hours a day should have so you are able to get a workday conversion.

**Comment by kevinkhill** [comment]
This is a good idea for expanding the library. The reason its only up to hours is because this library was initially created for calculating and converting runtimes of machinery, and we have no runtimes in days :laughing: 

I don't think it would be too hard to implement
