### ISSUE TITLE
toMinutes() method

### ISSUE THREAD

**Issue by dimitri-koenig** [kevinkhill/php-duration#4]
Cosmetic addition to return time in minutes, but still a useful one :-)

**Comment by kevinkhill** [comment]
and the method would return a float if not an even amount of minutes? or a rounded integer? Like is said in #3 about the specificity of the library, I only needed to store a duration in a database.

I would happily accept a pull request if you want to add the method.

**Comment by dimitri-koenig** [comment]
Thanks for merging

**Comment by kevinkhill** [comment]
Of course! That's the easiest part, thank you for contributing
