### ISSUE TITLE
Feature request: force displaying minutes/hours

### ISSUE THREAD

**Issue by gitomato** [kevinkhill/php-duration#7]
Thank you for this library which covers almost all of my needs.

I suggest a feature: if the duration is less than 1 minute, I would like to display `0:32` instead of `32`

We could imagine the same for hours: `0:00:32`

What do you think?

**Comment by kevinkhill** [comment]
So adding a zero fill to the humanize method? I don't think it's a bad idea at all. The only problem is that I don't have free time to work on this project. If you feel like adding the feature and writing a test for the test suite and prove it works, I'd happily accept a merge request

**Comment by AntonLazarev** [comment]
I would try to implement this feature, but I'm thinking of making different method, something like `formattedWithZeroes($showHours = false)`. Parameter $showHours decides how to show string `0:32` or `0:00:32`. What do you think about it?

**Comment by kevinkhill** [comment]
If you want to implement this, by all means go ahead! I'd be happy to merge it. 

All I ask is that you please follow my coding style and write tests for the feature.

**Comment by Ydalb** [comment]
Heya folk's, just opened a PR for this. Tell me how it looks like.

Regards,

**Comment by kevinkhill** [comment]
Merged!

**Comment by kevinkhill** [comment]
Thanks for the contribution 😊
